album_song_royalti/urls.py
from django.urls import path
from album_song_royalti.views import *

app_name = 'album_song_royalti'

urlpatterns = [
    path('royalti/', cek_royalti, name='cek_royalti'),
    path('create-album/', create_album, name='create_album'),
    path('create-song/', create_song, name='create_song'),
    path('list-album-label/', list_album_label, name='list_album_label'),
    path('list-album/', list_album, name='list_album'),
    path('list-song/', list_song, name='list_song'),
    path('delete-song/', delete_song, name='delete_song'),
    path('delete-album-label/', delete_album_label, name='delete_album_label'),
    path('delete-album-user/', delete_album_user, name='delete_album_user'),
    path('song_detail/', song_detail, name='song_detail'),
]

dashboard/urls.py
from django.urls import path
from dashboard.views import dashboard, search, downloaded_songs, delete_downloaded_song

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('songs/', downloaded_songs, name='downloaded_songs'),
    path('search/', search, name='search'),
    path('delete-song/', delete_downloaded_song, name='delete'),
]

marmut/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/auth/', permanent=False)),
    path('', include('album_song_royalti.urls')),
    path('', include('kelola_playlist.urls')),
    path('auth/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('kelola_podcast.urls')),
    path('', include('melihat_chart.urls')),
    path('', include('play_podcast.urls')),
    path('paket/', include('paket.urls')),
    path('', include('play_song.urls')),
]

paket/urls.py
from django.urls import path
from paket.views import paket, paket_payment, riwayat

app_name = 'paket'

urlpatterns = [
    path('', paket, name='paket'),
    path('riwayat/', riwayat, name='riwayat'),
    path('<str:nama_paket>/', paket_payment, name='paket_payment'),
]

album_song_royalti/views.py
from utils.query import get_database_cursor
from django.shortcuts import render, redirect
from django.shortcuts import render
import uuid
from django.shortcuts import redirect, render
from utils.query import *
from datetime import datetime
# Create your views here.
from django.http import HttpResponse


def create_album(request):
    isArtist = request.COOKIES.get('isArtist')
    isSongwriter = request.COOKIES.get('isSongwriter')
    id_user_artist = request.COOKIES.get('id_user_artist')
    id_user_songwriter = request.COOKIES.get('id_user_songwriter')

    if isArtist == "True":
        print(1)
        cursor.execute(
            f"SELECT email_akun FROM artist WHERE id = %s", [id_user_artist])
        email_artist = cursor.fetchone()
        cursor.execute(
            f"SELECT nama FROM akun WHERE email = %s", [email_artist[0]])
        nama_artist = cursor.fetchone()

    # Get songwriter name if the user is a songwriter
    if isSongwriter == "True":
        cursor.execute(
            f"SELECT email_akun FROM songwriter WHERE id = %s", [id_user_songwriter])
        email_songwriter = cursor.fetchone()
        cursor.execute(
            f"SELECT nama FROM akun WHERE email = %s", [email_songwriter[0]])
        nama_songwriter = cursor.fetchone()

    if request.method == 'POST':
        # Album creation part
        judul_album = request.POST.get('album-title')
        label = request.POST.get('album-label')
        id_album = str(uuid.uuid4())

        cursor.execute(
            'INSERT INTO album VALUES (%s, %s, 0, %s, 0)', (id_album, judul_album, label))
        connection.commit()

        # Check if song details are provided
        if 'song-title' in request.POST:
            judul_song = request.POST.get('song-title')
            durasi = request.POST.get('song-duration')
            songwriters = request.POST.getlist('song_writer[]')
            genres = request.POST.getlist('song_genre[]')
            id_song = str(uuid.uuid4())
            current_datetime = datetime.now()
            date_now = current_datetime.strftime('%Y-%m-%d')
            year_now = '{:04d}'.format(current_datetime.year)

            # Handle artist information
            if isArtist == "True":
                id_pemilik_hak_cipta_artist = request.COOKIES.get(
                    'idPemilikCiptaArtist')
            else:
                id_user_artist = request.POST.get('song_artist')
                cursor.execute(
                    "SELECT id_pemilik_hak_cipta FROM artist WHERE id = %s", [id_user_artist])
                id_pemilik_hak_cipta_artist = cursor.fetchone()[0]

            # Insert into 'konten' table
            cursor.execute(
                "INSERT INTO konten VALUES (%s, %s, %s, %s, %s)",
                (id_song, judul_song, date_now, year_now, durasi)
            )

            # Insert into 'song' table
            cursor.execute(
                "INSERT INTO song VALUES (%s, %s, %s, 0, 0)",
                (id_song, id_user_artist, id_album)
            )

            # Insert into 'songwriter_write_song' and 'royalti' tables
            for songwriter in songwriters:
                cursor.execute(
                    "SELECT id_pemilik_hak_cipta FROM songwriter WHERE id = %s", [songwriter])
                id_pemilik_hak_cipta_songwriter = cursor.fetchone()[0]
                cursor.execute(
                    "INSERT INTO royalti VALUES (%s, %s, 0)",
                    (id_pemilik_hak_cipta_songwriter, id_song)
                )
                cursor.execute(
                    "INSERT INTO songwriter_write_song VALUES (%s, %s)",
                    (songwriter, id_song)
                )

            # Insert into 'genre' table
            for genre in genres:
                cursor.execute(
                    "INSERT INTO genre VALUES (%s, %s)",
                    (id_song, genre)
                )

            # Insert into 'royalti' table for artist
            cursor.execute(
                "INSERT INTO royalti VALUES (%s, %s, 0)",
                (id_pemilik_hak_cipta_artist, id_song)
            )

            # Insert into 'royalti' table for label
            cursor.execute(
                "SELECT id_label FROM album WHERE id = %s", [id_album])
            id_label = cursor.fetchone()
            if id_label:
                id_label = id_label[0]
                cursor.execute(
                    "SELECT id_pemilik_hak_cipta FROM label WHERE id = %s", [id_label])
                id_pemilik_hak_cipta_label = cursor.fetchone()
                if id_pemilik_hak_cipta_label:
                    id_pemilik_hak_cipta_label = id_pemilik_hak_cipta_label[0]
                    cursor.execute(
                        "INSERT INTO royalti VALUES (%s, %s, 0)",
                        (id_pemilik_hak_cipta_label, id_song)
                    )

            # Update album information
            cursor.execute(
                "SELECT jumlah_lagu, total_durasi FROM album WHERE id = %s", [id_album])
            album_saat_ini = cursor.fetchone()
            new_total_durasi = int(album_saat_ini[1]) + int(durasi)
            new_jumlah_lagu = int(album_saat_ini[0]) + 1
            cursor.execute(
                "UPDATE album SET jumlah_lagu = %s, total_durasi = %s WHERE id = %s",
                (new_jumlah_lagu, new_total_durasi, id_album)
            )

            # Commit changes to the database
            connection.commit()
            update_album_details(id_album)
            return redirect('album_song_royalti:list_album')

    cursor.execute('SELECT id, nama FROM label')
    list_label = cursor.fetchall()

    cursor.execute("SELECT id, email_akun, id_pemilik_hak_cipta FROM artist")
    records_artist = cursor.fetchall()
    for i in range(len(records_artist)):
        cursor.execute("SELECT nama FROM akun WHERE email = %s",
                       [records_artist[i][1]])
        records_artist[i] = records_artist[i] + cursor.fetchone()

    cursor.execute(
        "SELECT id, email_akun, id_pemilik_hak_cipta FROM songwriter")
    records_songwriter = cursor.fetchall()
    for i in range(len(records_songwriter)):
        cursor.execute("SELECT nama FROM akun WHERE email = %s",
                       [records_songwriter[i][1]])
        records_songwriter[i] = records_songwriter[i] + cursor.fetchone()

    cursor.execute("SELECT DISTINCT genre FROM genre")
    records_genre = cursor.fetchall()

    context = {
        'list_label': list_label,
        'records_artist': records_artist,
        'records_songwriter': records_songwriter,
        'records_genre': records_genre,
        'isArtist': isArtist,
        'isSongwriter': isSongwriter,
        'id_user_artist': id_user_artist,
        'id_user_songwriter': id_user_songwriter,
        'artist_name': nama_artist,
        'songwriter_name': nama_songwriter,
    }

    return render(request, 'create_album.html', context)


def create_song(request):
    connection, cursor = get_database_cursor()
    # Get values from cookies
    isArtist = request.COOKIES.get('isArtist')
    isSongwriter = request.COOKIES.get('isSongwriter')
    id_user_artist = request.COOKIES.get('id_user_artist')
    id_user_songwriter = request.COOKIES.get('id_user_songwriter')
    album_id = request.GET.get('id') or request.POST.get('id')

    # Initialize names
    nama_artist = ""
    nama_songwriter = ""

    if request.method == 'POST':
        album_id = request.POST.get('album_id')
        if not album_id:
            return HttpResponse("Album ID is required", status=400)

        # Get POST data
        judul = request.POST.get('song-title')
        id_song = str(uuid.uuid4())
        durasi = request.POST.get('song-duration')
        current_datetime = datetime.now()
        date_now = current_datetime.strftime('%Y-%m-%d')
        year_now = current_datetime.year
        songwriters = request.POST.getlist('song_writer[]')
        genres = request.POST.getlist('song_genre[]')

        # Handle artist information
        if isArtist == "True":
            id_pemilik_hak_cipta_artist = request.COOKIES.get(
                'idPemilikCiptaArtist')
        else:
            id_user_artist = request.POST.get('song_artist')
            cursor.execute("SELECT id_pemilik_hak_cipta FROM artist WHERE id = %s", [
                           id_user_artist])
            id_pemilik_hak_cipta_artist = cursor.fetchone()[0]

        # Insert song and related data
        cursor.execute(
            "INSERT INTO konten (id, judul, tanggal_rilis, tahun, durasi) VALUES (%s, %s, %s, %s, %s)",
            (id_song, judul, date_now, year_now, durasi)
        )
        cursor.execute(
            "INSERT INTO song (id_konten, id_artist, id_album, total_play, total_download) VALUES (%s, %s, %s, 0, 0)",
            (id_song, id_user_artist, album_id)
        )
        cursor.executemany(
            "INSERT INTO songwriter_write_song (id_songwriter, id_song) VALUES (%s, %s)",
            [(songwriter, id_song) for songwriter in songwriters]
        )
        cursor.executemany(
            "INSERT INTO genre (id_konten, genre) VALUES (%s, %s)",
            [(id_song, genre) for genre in genres]
        )
        cursor.executemany(
            "INSERT INTO royalti (id_pemilik_hak_cipta, id_song, jumlah) VALUES (%s, %s, 0)",
            [(id_pemilik_hak_cipta_artist, id_song)] +
            [(cursor.execute("SELECT id_pemilik_hak_cipta FROM songwriter WHERE id = %s", [
              songwriter]).fetchone()[0], id_song) for songwriter in songwriters]
        )

        cursor.execute("SELECT id_label FROM album WHERE id = %s", [album_id])
        id_label = cursor.fetchone()
        if id_label:
            id_label = id_label[0]
            cursor.execute(
                "SELECT id_pemilik_hak_cipta FROM label WHERE id = %s", [id_label])
            id_pemilik_hak_cipta_label = cursor.fetchone()
            if id_pemilik_hak_cipta_label:
                cursor.execute(

album_song_royalti/templates/cek_royalti.html
{% extends 'base_user.html' %}
{% load static %}

{% block meta %}
<head>
    <title>List Royalti</title>
</head>
{% endblock meta %}

{% block content %}
<div class="container mt-4">
  <h1 class="mb-4">List Royalti
    <small class="text-muted">
      {% if request.COOKIES.isArtist == 'True' %}
        Artist
      {% endif %}
      {% if request.COOKIES.isSongwriter == 'True' %}
        {% if request.COOKIES.isArtist == 'True' %}, {% endif %}Songwriter
      {% endif %}
      {% if request.COOKIES.isPodcaster == 'True' %}
        {% if request.COOKIES.isArtist == 'True' or request.COOKIES.isSongwriter == 'True' %}, {% endif %}Podcaster
      {% endif %}
    </small>
  </h1>
  <table class="table table-striped table-bordered">
    <thead class="table-dark">
      <tr>
        <th colspan="5" class="text-center">Daftar Royalti</th>
      </tr>
      <tr>
        <th>Judul Lagu</th>
        <th>Judul Album</th>
        <th>Total Play</th>
        <th>Total Download</th>
        <th>Total Royalti Didapat</th>
      </tr>
    </thead>
    <tbody>
      <!-- Placeholder for Royalti list -->
      {% for record in all_royalti %}
      <tr class="text-white">
          <td class="py-3 px-4">{{ record.1 }}</td>
          <td class="py-3 px-4">{{ record.2 }}</td>
          <td class="py-3 px-4">{{ record.3 }}</td>
          <td class="py-3 px-4">{{ record.4 }}</td>
          <td class="py-3 px-4">Rp {{ record.5 }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

album_song_royalti/templates/create_album.html
{% extends 'base_user.html' %}
{% load static %}

{% block meta %}
<head>
    <title>Create Album and Song</title>
</head>
{% endblock meta %}

{% block content %}
<div class="container mt-4">
  <h1 class="mb-4">Create Album and Song</h1>
  <form method="post" action="{% url 'album_song_royalti:create_album' %}">
    {% csrf_token %}
    
    <!-- Album Information -->
    <div class="mb-3">
      <label for="album-title" class="form-label">Album Title</label>
      <input type="text" class="form-control" id="album-title" name="album-title" required>
    </div>
    <div class="mb-3">
      <label for="album-label" class="form-label">Album Label</label>
      <select class="form-control" id="album-label" name="album-label" required>
        {% for label in list_label %}
          <option value="{{ label.0 }}">{{ label.1 }}</option>
        {% endfor %}
      </select>
    </div>
    
    <!-- Song Information -->
    <div class="mb-3">
      <label for="song-title" class="form-label">Judul Lagu:</label>
      <input type="text" id="song-title" name="song-title" class="form-control" required />
    </div>
    {% if isArtist == "True" %}
      <div class="mb-3">
        <label for="song-artist" class="form-label">Artis: {{ artist_name.0 }}</label>
      </div>
    {% else %}
      <div class="mb-3">
        <label for="song-artist" class="form-label">Artis:</label>
        <select id="song-artist" name="song_artist" class="form-select" required>
          <option value="">Pilih Artis</option>
          {% for record in records_artist %}
          <option value="{{ record.0 }}">{{ record.3 }}</option>
          {% endfor %}
        </select>
      </div>
    {% endif %}
    
    {% if isSongwriter == "True" %}
    <div class="mb-3">
      <label for="song-writer" class="form-label">Songwriter: {{ songwriter_name.0 }}</label>
    </div>
    {% else %}
    <div class="mb-3">
      <label for="song-writer" class="form-label">Songwriter:</label>
      <select id="song-writer" name="song_writer[]" class="form-select" multiple required>
        <option value="">Pilih Songwriter</option>
        {% for record in records_songwriter %}
        <option value="{{ record.0 }}">{{ record.3 }}</option>
        {% endfor %}
      </select>
    </div>
    {% endif %}
    
    <div class="mb-3">
      <label for="song-genre" class="form-label">Genre:</label>
      <select id="song-genre" name="song_genre[]" class="form-select" multiple required>
        {% for record in records_genre %}
        <option value="{{ record.0 }}">{{ record.0 }}</option>
        {% endfor %}
      </select>
    </div>
  
    <div class="mb-3">
      <label for="song-duration" class="form-label">Durasi (menit):</label>
      <input type="text" id="song-duration" name="song-duration" class="form-control" required />
    </div>
  
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}

album_song_royalti/templates/create_songs.html
{% extends 'base_user.html' %}
{% load static %}

{% block meta %}
<head>
    <title>Create Songs</title>
</head>
{% endblock meta %}

{% block content %}
<h1>Create Lagu</h1>

<div class="mb-3">
  
<form action="{% url 'album_song_royalti:create_song' %}" method="post">
{% csrf_token %}
  <div class="mb-3">
    <label for="song-album" class="form-label">Album: {{ judul_album.0 }}</label>
    <input type="hidden" name="album_id" value="{{ album_id }}"> <!-- Hidden input for Album ID -->
  </div>
  <div class="mb-3">
    <label for="song-title" class="form-label">Judul Lagu:</label>
    <input type="text" id="song-title" name="song-title" class="form-control" required />
  </div>
  {% if isArtist == "True" %}
    <div class="mb-3">
      <label for="song-artist" class="form-label">Artis: {{ artist_name.0 }}</label>
    </div>
  {% else %}
    <div class="mb-3">
      <label for="song-artist" class="form-label">Artis:</label>
      <select id="song-artist" name="song_artist" class="form-select" required>
        <option value="">Pilih Artis</option>
        {% for record in records_artist %}
        <option value="{{ record.0 }}">{{ record.3 }}</option>
        {% endfor %}
      </select>
    </div>
  {% endif %}
  
  {% if isSongwriter == "True" %}
  <div class="mb-3">
    <label for="song-writer" class="form-label">Songwriter: {{ songwriter_name.0 }}</label>
  </div>
  {% else %}
  <div class="mb-3">
    <label for="song-writer" class="form-label">Songwriter:</label>
    <select id="song-writer" name="song_writer[]" class="form-select" multiple required>
      <option value="">Pilih Songwriter</option>
      {% for record in records_songwriter %}
      <option value="{{ record.0 }}">{{ record.3 }}</option>
      {% endfor %}
    </select>
  </div>
  {% endif %}
  
  <div class="mb-3">
    <label for="song-genre" class="form-label">Genre:</label>
    <select id="song-genre" name="song_genre[]" class="form-select" multiple required>
      {% for record in records_genre %}
      <option value="{{ record.0 }}">{{ record.0 }}</option>
      {% endfor %}
    </select>
  </div>

  <div class="mb-3">
    <label for="song-duration" class="form-label">Durasi (menit):</label>
    <input type="text" id="song-duration" name="song-duration" class="form-control" required />
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

album_song_royalti/templates/detail_song.html
{% extends 'base_user.html' %}
{% load static %}

{% block meta %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Song Detail</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .song-detail {
            border: 1px solid #ccc;
            padding: 20px;
            max-width: 600px;
            margin: 20px auto;
        }
        .song-info {
            margin-bottom: 20px;
        }
        .controls {
            text-align: center;
        }
        .controls button {
            margin-bottom: 10px;
        }
        .navbar {
            justify-content: flex-end;
        }
        .navbar-nav {
            flex-direction: row;
        }
        .navbar-collapse {
            justify-content: flex-end;
        }
    </style>
</head>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="song-detail">
        <h2 class="text-center">SONG DETAILS</h2>
        <div class="container">
            <p><strong>Judul:</strong> {{ song.judul }}</p>
            <p><strong>Genre(s):</strong></p>
            <ul>
                <li><strong>-</strong> {{ song.genre }}</li>
            </ul>
            <p><strong>Artist:</strong> {{ song.artist }}</p>
            <p><strong>Songwriter(s):</strong></p>
            <ul>
                <li><strong>-</strong> {{ song.songwriters }}</li>
            </ul>
            <p><strong>Durasi:</strong> {{ song.durasi }} menit</p>
            <p><strong>Tanggal Rilis:</strong> {{ song.tanggal_rilis }}</p>
            <p><strong>Tahun:</strong> {{ song.tahun }}</p>
            <p><strong>Total Play:</strong> {{ song.total_play }}</p>
            <p><strong>Total Downloads:</strong> {{ song.total_download }}</p>
            <p><strong>Album:</strong> {{ song.album }}</p>
            <div class="divider"></div>
            <div class="actions">
                <a href="#" class="btn btn-primary" onclick="window.location.href='{% url 'dashboard:dashboard' %}'">Kembali ke Dashboard</a>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock content %}

album_song_royalti/templates/list_album.html
{% extends 'base_user.html' %}
{% load static %}

{% block meta %}
<head>
    <title>List Album</title>
</head>
{% endblock meta %}

{% block content %}
<div class="container mt-5">
  <h1>List Album</h1>

  <button class="btn btn-success mb-3" onclick="location.href='{% url 'album_song_royalti:create_album' %}'">Tambah Album</button>

  <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="5">Daftar Album</th>
      </tr>
      <tr>
        <th>Judul</th>
        <th>Label</th>
        <th>Jumlah Lagu</th>
        <th>Total Durasi</th>
        <th>Aksi</th>
      </tr>
    </thead>
    <tbody>
      {% for record in list_albums %}
      <tr>
        <td>{{ record.1 }}</td>
        <td>{{ record.5 }}</td>
        <td>{{ record.3 }}</td>
        <td>{{ record.4 }}</td>
        <td>
          <button class="btn btn-primary btn-sm" onclick="window.location.href='{% url 'album_song_royalti:list_song' %}?id={{ record.0 }}'">Lihat Daftar Lagu</button>
          <button class="btn btn-warning btn-sm" onclick="window.location.href='{% url 'album_song_royalti:create_song' %}?id={{ record.0 }}'">Tambah Lagu</button>
          <button class="btn btn-danger btn-sm" onclick="window.location.href='{% url 'album_song_royalti:delete_album_user' %}?id={{ record.0 }}'">Hapus</button>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

album_song_royalti/templates/list_album_label.html
{% extends 'base_user.html' %}
{% load static %}

{% block meta %}
<head>
    <title>List Album</title>
</head>
{% endblock meta %}

{% block content %}
<div class="container mt-5">
  <h1>List Album</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="5">Daftar Album</th>
      </tr>
      <tr>
        <th>Judul</th>
        <th>Jumlah Lagu</th>
        <th>Total Durasi</th>
        <th>Aksi</th>
      </tr>
    </thead>
    <tbody>
      {% for record in list_albums %}
      <tr>
        <td>{{record.1}}</td>
        <td>{{record.2}}</td>
        <td>{{record.3}} Menit</td>
        <td>
          <button class="btn btn-primary btn-sm" onclick="window.location.href='{% url 'album_song_royalti:list_song' %}?id={{ record.0 }}'">Lihat Daftar Lagu</button>
          <button class="btn btn-danger btn-sm" onclick="window.location.href='{% url 'album_song_royalti:delete_album_label' %}?id={{ record.0 }}'">Hapus</button>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

album_song_royalti/templates/list_songs.html
{% extends 'base_user.html' %}
{% load static %}

{% block meta %}
<head>
    <title>List Songs</title>
</head>
{% endblock meta %}

{% block content %}
<div class="container mt-5">
  <h1>Daftar Lagu dalam Album</h1>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th colspan="5">Daftar Lagu</th>
      </tr>
      <tr>
        <th>Judul</th>
        <th>Durasi</th>
        <th>Total Play</th>
        <th>Total Download</th>
        <th>Aksi</th>
      </tr>
    </thead>
    <tbody id="song-list">
      {% for record in list_songs%}
      <tr>
        <td>{{record.3}}</td>
        <td>{{record.6}}</td>
        <td>{{record.1}}</td>
        <td>{{record.2}}</td>
        <td>
          <button class="btn btn-primary btn-sm" onclick="window.location.href='{% url 'album_song_royalti:song_detail' %}?song_id={{ record.0 }}'">Lihat Detail</button>
          <button class="btn btn-danger btn-sm" onclick="window.location.href='{% url 'album_song_royalti:delete_song' %}?song_id={{ record.0 }}'">Hapus</button>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}