kelola_playlist/urls.py
from django.urls import path
from . import views
from kelola_playlist.views import playlist, playlist_detail, tambah_playlist, delete_playlist, edit_playlist, tambah_lagu, delete_song

app_name = 'kelola_playlist'

urlpatterns = [
    path('playlist/', playlist, name='playlist'),
    path('playlist_detail/<uuid:idPlaylist>/', playlist_detail, name='playlist_detail'),
    path('tambah_lagu/<uuid:idPlaylist>/', tambah_lagu, name='tambah_lagu'),
    path('tambah_playlist/', tambah_playlist, name='tambah_playlist'),
    path('delete_playlist/<uuid:idPlaylist>/', delete_playlist, name='delete_playlist'),
    path('edit_playlist/<uuid:idPlaylist>/', edit_playlist, name='edit_playlist'),
    path('delete_song/<uuid:playlist_id>/<uuid:song_id>/', delete_song, name='delete_song'),
   
]

marmut/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/auth/', permanent=False)),
    path('', include('album_song_royalti.urls')),
    path('', include('kelola_playlist.urls')),
    path('auth/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('kelola_podcast.urls')),
    path('', include('melihat_chart.urls')),
    path('', include('play_podcast.urls')),
    path('paket/', include('paket.urls')),
    path('', include('play_song.urls')),
]

paket/urls.py
from django.urls import path
from paket.views import paket, paket_payment, riwayat

app_name = 'paket'

urlpatterns = [
    path('', paket, name='paket'),
    path('riwayat/', riwayat, name='riwayat'),
    path('<str:nama_paket>/', paket_payment, name='paket_payment'),
]

play_song/urls.py
from django.urls import path
from . import views
from play_song.views import song_detail, song_detail_only, add_to_playlist_new, add_to_playlist

app_name = 'play_song'

urlpatterns = [   
    path('song_detail/<uuid:playlist_id>/<uuid:song_id>/', song_detail, name='song_detail'),
    path('song_detail/<uuid:song_id>/', song_detail_only, name='song_detail_only'),
    path('add_to_playlist/<uuid:playlist_id>/<uuid:song_id>/', add_to_playlist, name='add_to_playlist'),
    path('add_to_playlist/<uuid:song_id>/', add_to_playlist_new, name='add_to_playlist_new'),
    
]

kelola_playlist/forms.py
from django import forms

class AddUserPlaylistForm(forms.Form):
    judul = forms.CharField(max_length=100, label='Judul')
    deskripsi = forms.CharField(max_length=500, label='Deskripsi', widget=forms.Textarea)

class EditUserPlaylistForm(forms.Form):
    judul = forms.CharField(label='Judul', max_length=100)
    deskripsi = forms.CharField(label='Deskripsi', widget=forms.Textarea)

kelola_playlist/views.py
from http.client import HTTPResponse
from pyexpat.errors import messages
from utils.query import *
from django.db import connection
from function.general import query_result
from django.http import HttpResponseRedirect
from django.core import serializers
from kelola_playlist.forms import AddUserPlaylistForm, EditUserPlaylistForm
from django.urls import reverse
from django.db import connection
import datetime
import uuid
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseNotAllowed, HttpResponseForbidden
from django.views.decorators.csrf import csrf_protect


def playlist(request):
    connection, cursor = get_database_cursor()
    email = request.COOKIES.get('email')
    cursor.execute(f"""
            SELECT * FROM user_playlist where email_pembuat = '{email}';
        """)
    playlists = cursor.fetchall()

    context = {'playlists': playlists}
    cursor.close()
    connection.close()
    return render(request, 'playlist.html', context)

def convert_to_hours_minutes(total_minutes):
    hours = total_minutes // 60
    minutes = total_minutes % 60
    return hours, minutes

def playlist_detail(request, idPlaylist):
    connection, cursor = get_database_cursor()
    success_message = None
    
    # Fetch email of the current user
    email = request.COOKIES.get('email')

    # Retrieve playlist details
    cursor.execute("""
        SELECT UP.judul, UP.deskripsi, UP.tanggal_dibuat, A.nama AS pembuat_playlist, 
               COUNT(PS.id_song) AS jumlah_lagu, COALESCE(SUM(K.durasi), 0) AS total_durasi,
               UP.email_pembuat
        FROM marmut.user_playlist AS UP
        JOIN marmut.akun AS A ON UP.email_pembuat = A.email
        LEFT JOIN marmut.playlist_song AS PS ON UP.id_playlist = PS.id_playlist
        LEFT JOIN marmut.konten AS K ON PS.id_song = K.id
        WHERE UP.id_playlist = %s
        GROUP BY UP.judul, UP.deskripsi, UP.tanggal_dibuat, A.nama, UP.email_pembuat;
    """, [idPlaylist])
    playlist = cursor.fetchone()

    if not playlist:
        return HTTPResponse("Playlist not found", status=404)

    email_pembuat = playlist[6]  # Fetch the email_pembuat from the playlist details

    # Check if the user_playlist exists before attempting to insert into akun_play_user_playlist
    cursor.execute("SELECT COUNT(*) FROM marmut.user_playlist WHERE id_playlist = %s AND email_pembuat = %s", [idPlaylist, email_pembuat])
    user_playlist_count = cursor.fetchone()[0]

    if user_playlist_count == 0:
        return HTTPResponse("User Playlist not found", status=404)

    # Retrieve song details
    cursor.execute("""
        SELECT K.judul, K.durasi, K.tanggal_rilis, A.nama AS oleh, K.id
        FROM marmut.playlist_song AS PS
        JOIN marmut.konten AS K ON K.id = PS.id_song
        JOIN marmut.song AS S ON S.id_konten = K.id
        JOIN marmut.artist AS AT ON AT.id = S.id_artist
        JOIN marmut.akun AS A ON A.email = AT.email_akun
        WHERE PS.id_playlist = %s;
    """, [idPlaylist])
    songs = cursor.fetchall()

    total_minutes = playlist[5]
    hours, minutes = convert_to_hours_minutes(total_minutes)

    if request.method == 'POST':
        if 'shuffle_play' in request.POST:
            current_timestamp = datetime.datetime.now()

            # Insert ke tabel AKUN_PLAY_PLAYLIST 
            cursor.execute("""
                INSERT INTO marmut.akun_play_user_playlist (email_pemain, id_user_playlist, email_pembuat, waktu)
                VALUES (%s, %s, %s, %s)
            """, (email, idPlaylist, email_pembuat, current_timestamp))

            connection.commit()

            # Insert ke tabel AKUN_PLAY_SONG untuk setiap lagu dalam playlist 
            for song in songs:
                song_id = song[4]
                current_timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                cursor.execute("""
                    INSERT INTO marmut.akun_play_song (email_pemain, id_song, waktu)
                    VALUES (%s, %s, %s)
                """, (email, song_id, current_timestamp))

            connection.commit()
            
            return redirect(reverse("playlist_player:play_user_playlist") + f'?playlist_id={idPlaylist}')
        
        else:
            for song in songs:
                song_id = song[4]
                if f'play_song_{song_id}' in request.POST:
                    current_timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                    cursor.execute("SELECT total_play FROM marmut.song WHERE id_konten = %s", [song_id])
                    total = cursor.fetchone()
                    total_play = total[0] + 1

                    cursor.execute("UPDATE marmut.song SET total_play = %s WHERE id_konten = %s", [total_play, song_id])
                    cursor.execute("""
                        INSERT INTO marmut.akun_play_song (email_pemain, id_song, waktu)
                        VALUES (%s, %s, %s)
                    """, (email, song_id, current_timestamp))

                    connection.commit()

    context = {
        'playlist': {
            'judul': playlist[0],
            'deskripsi': playlist[1],
            'tanggal_dibuat': playlist[2],
            'pembuat_playlist': playlist[3],
            'jumlah_lagu': playlist[4],
            'total_durasi_hours': hours,
            'total_durasi_minutes': minutes,
            'idPlaylist': idPlaylist,
        },
        'songs': [
            {
                'judul': song[0],
                'oleh': song[3],
                'durasi': song[1],
                'id': song[4]
            }
            for song in songs
        ],
    }

    cursor.close()
    connection.close()

    return render(request, 'playlist_detail.html', context)


def delete_playlist(request, idPlaylist):
    connection, cursor = get_database_cursor()

    try:
        # Check if the playlist exists
        cursor.execute("""
            SELECT id_playlist 
            FROM user_playlist 
            WHERE id_playlist = %s;
        """, [idPlaylist])

        playlist = cursor.fetchone()

        if playlist:
            # Fetch songs associated with the playlist
            cursor.execute("""
                SELECT id_song 
                FROM playlist_song 
                WHERE id_playlist = %s;
            """, [idPlaylist])

            songs = cursor.fetchall()

            # Delete each song associated with the playlist
            for song in songs:
                song_id = song[0]
                cursor.execute("""
                    DELETE FROM playlist_song 
                    WHERE id_playlist = %s AND id_song = %s;
                """, [idPlaylist, song_id])

            # Now delete the playlist
            cursor.execute("""
                DELETE FROM user_playlist 
                WHERE id_playlist = %s;
            """, [idPlaylist])

            connection.commit()
        else:
            return HttpResponseForbidden("The playlist does not exist.")
    finally:
        cursor.close()
        connection.close()

    # Redirect to the list_playlist page after successful deletion
    return redirect('kelola_playlist:playlist')

def edit_playlist(request, idPlaylist):
    with connection.cursor() as cursor:
        cursor.execute(f"SELECT * FROM marmut.user_playlist WHERE id_playlist = '{idPlaylist}';")
        playlist = cursor.fetchone()
        
        if not playlist:
            return HTTPResponse("Playlist not found", status=404)

        if request.method == 'POST':
            form = EditUserPlaylistForm(request.POST)
            if form.is_valid():
                judul = form.cleaned_data['judul']
                deskripsi = form.cleaned_data['deskripsi']
                
                cursor.execute("""
                UPDATE marmut.user_playlist
                SET judul = %s, deskripsi = %s
                WHERE id_playlist = %s;
                """, [judul, deskripsi, idPlaylist])
                
                return redirect('kelola_playlist:playlist')
        else:
            form = EditUserPlaylistForm(initial={'judul': playlist[2], 'deskripsi': playlist[3]})
    
    context = {'form': form, 'playlist_id': idPlaylist}
    return render(request, 'edit_playlist.html', context)

def tambah_playlist(request):
    if request.method == 'POST':
        judul = request.POST.get('judul')
        deskripsi = request.POST.get('deskripsi')

        # Generate UUID baru
        id_playlist = str(uuid.uuid4())
        connection, cursor = get_database_cursor()

        # Insert playlist baru
        cursor.execute("INSERT INTO playlist (id) VALUES (%s);", [id_playlist])

        # Insert data ke "user_playlist" 
        email_pembuat = request.COOKIES.get('email')  
        jumlah_lagu = 0
        tanggal_dibuat = datetime.date.today()  
        id_user_playlist = str(uuid.uuid4())  
        total_durasi = 0

        cursor.execute("""
            INSERT INTO user_playlist 
            (email_pembuat, judul, deskripsi, jumlah_lagu, tanggal_dibuat, id_user_playlist, id_playlist, total_durasi) 
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s);""",
            [email_pembuat, judul, deskripsi, jumlah_lagu, tanggal_dibuat, id_user_playlist, id_playlist, total_durasi])
        
        context = {
            'email_pembuat' : email_pembuat
        }
        
        connection.commit()
        cursor.close()
        connection.close()

        # sukses
        return redirect('kelola_playlist:playlist')
    else:
        email_pembuat = request.COOKIES.get('email') 
        context = {
            'email_pembuat' : email_pembuat
        }
        return render(request, 'tambah_playlist.html', context)
    
def tambah_lagu(request, idPlaylist):
    if request.method == 'POST':
        song_id = request.POST.get('song_id')

        # Pastikan song_id tidak kosong atau None
        if song_id:
            # Dapatkan koneksi dan kursor sebelum melakukan operasi database

kelola_playlist/templates/edit_playlist.html
{% extends 'base_user.html' %}
{% load static %}

{% block meta %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
</head>

{% endblock meta %}

{% block content %}

    <h1>Edit Playlist</h1>

    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Edit Playlist">
                </td>
            </tr>
        </table>
    </form>

<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock content %}

kelola_playlist/templates/playlist.html
{% extends 'base_user.html' %}
{% load static %}

{% block meta %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Playlist - Marmut</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
{% endblock meta %}

{% block content %}

    <div class="container-fluid">

        <div class="playlist-box">
            <h2 class="text-center">User Playlist</h2>

            <div class="container">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Judul</th>
                            <th scope="col">Jumlah Lagu</th>
                            <th scope="col">Total Durasi</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                      {% for playlist in playlists %}
                      <tr>
                          <td>{{ playlist.2 }}</td>
                          <td>{{ playlist.4 }}</td>
                          <td>{{ playlist.7 }} menit</td>
                          <td>
                              <a href="{% url 'kelola_playlist:playlist_detail' idPlaylist=playlist.6 %}" class="btn btn-primary">Detail</a>
                              <a href="{% url 'kelola_playlist:edit_playlist' idPlaylist=playlist.6 %}" class="btn btn-secondary">Edit</a>
                              <form action="{% url 'kelola_playlist:delete_playlist' idPlaylist=playlist.6 %}" method="POST" style="display:inline;">
                                  {% csrf_token %}
                                  <button type="submit" class="btn btn-danger" onclick="return confirm('Apakah Anda yakin ingin menghapus playlist ini?');">Delete</button>
                              </form>
                          </td>
                      </tr>
                      {% endfor %}                      
                        
                    </tbody>
                </table>
            </div>

            <p class="text-center"><a href="{% url 'kelola_playlist:tambah_playlist' %}" class="btn btn-success">Tambah Playlist</a></p>
        </div>

    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock content %}

kelola_playlist/templates/playlist_detail.html
{% extends 'base_user.html' %}
{% load static %}

{% block meta %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Playlist - Marmut</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
{% endblock meta %}

{% block content %}

        <div class="playlist-box">
            <h2>User Playlist Detail</h2>
            <p>Judul: {{playlist.judul}}</p>
            <p>Pembuat: {{playlist.pembuat_playlist}}</p>
            <p>Jumlah Lagu: {{playlist.jumlah_lagu}}</p>
            <p>Total Durasi: {{playlist.total_durasi_hours}} jam {{playlist.total_durasi_minutes}} menit</p>
            <p>Tanggal Dibuat: {{playlist.tanggal_dibuat}}</p>
            <p>Deskripsi: {{playlist.deskripsi}}</p>
            <form method="post">
              {% csrf_token %}
              <button type="submit" name="shuffle_play" class="btn btn-primary">Shuffle Play</button>
            </form>
            <a href="{% url 'kelola_playlist:playlist' %}" class="btn btn-secondary">Kembali</a>

            <div class="song-list" style="margin-top: 30px;">

                <h3>DAFTAR LAGU</h3>
                <table>
                    <tr>
                        <th>Judul Lagu</th>
                        <th>Oleh</th>
                        <th>Durasi</th>
                        <th>Actions</th>
                    </tr>
                    {% for song in songs %}
                    <tr>
                        <td>{{ song.judul }}</td>
                        <td>{{ song.oleh }}</td>
                        <td>{{ song.durasi }} menit</td>
                        <td>
                          <a href="{% url 'play_song:song_detail' playlist.idPlaylist song.id %}" class="btn btn-primary">Lihat</a>
                          <!-- <form method="post" style="display:inline;">
                              {% csrf_token %}
                              <button type="submit" name="play_song_{{ song.id }}" class="btn btn-success">Play</button>
                          </form> -->
                          <a href="{% url 'play_song:song_detail' playlist.idPlaylist song.id %}" class="btn btn-success">Play</a>
                            <a href="{% url 'kelola_playlist:delete_song' playlist.idPlaylist song.id %}" class="btn btn-danger">Hapus</a>
                        </td>
                    </tr>
                    {% endfor %}
    
                </table>
                <a href="{% url 'kelola_playlist:tambah_lagu' playlist.idPlaylist %}" class="btn btn-primary">Tambah Lagu</a>
            </div>
        </div>
    </div>
<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock content %}

kelola_playlist/templates/playlist_kosong.html
{% extends 'base_user.html' %}
{% load static %}

{% block meta %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Playlist - Marmut</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>

{% endblock meta %}

{% block content %}
    <div class="container">
        <div class="playlist-box">
            <h2 class="mt-3">User Playlist</h2>
            <!-- Jika belum ada playlist -->
            <p>Anda Belum Memiliki Playlist</p>
            <a href="tambah_playlist.html" class="btn btn-primary">Tambah Playlist</a>
        </div>
    </div>

<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock content %}

kelola_playlist/templates/tambah_lagu.html
{% extends 'base_user.html' %}
{% load static %}

{% block meta %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Playlist - Marmut</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>

{% endblock meta %}

{% block content %}

    <div class="container">
        <h1>Tambah Lagu</h1>
        {% if error_message %}
            <div class="alert alert-danger">{{ error_message }}</div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <label for="song">Lagu:</label>
            <select id="song" name="song_id">
                <option value="">Pilih Lagu</option>
                {% for song in songs %}
                    <option value="{{ song.0 }}">{{ song.1 }} - {{ song.2 }}</option>
                {% endfor %}
            </select>
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>

<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock content %}

kelola_playlist/templates/tambah_playlist.html
{% extends 'base_user.html' %}
{% load static %}

{% block meta %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tambah Playlist - Marmut</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    
</head>
{% endblock meta %}

{% block content %}
    <div class="container">
        <div class="add-playlist-container">
            <h2>Tambah Playlist</h2>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="judul" class="col-sm-3 col-form-label">Judul</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="judul" name="judul">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="deskripsi" class="col-sm-3 col-form-label">Deskripsi</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="deskripsi" name="deskripsi">
                    </div>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>

<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock content %}