album_song_royalti/urls.py
from django.urls import path
from album_song_royalti.views import *

app_name = 'album_song_royalti'

urlpatterns = [
    path('royalti/', cek_royalti, name='cek_royalti'),
    path('create-album/', create_album, name='create_album'),
    path('create-song/', create_song, name='create_song'),
    path('list-album-label/', list_album_label, name='list_album_label'),
    path('list-album/', list_album, name='list_album'),
    path('list-song/', list_song, name='list_song'),
    path('delete-song/', delete_song, name='delete_song'),
    path('delete-album-label/', delete_album_label, name='delete_album_label'),
    path('delete-album-user/', delete_album_user, name='delete_album_user'),
    path('song_detail/', song_detail, name='song_detail'),
]

dashboard/urls.py
from django.urls import path
from dashboard.views import dashboard, search, downloaded_songs, delete_downloaded_song

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('songs/', downloaded_songs, name='downloaded_songs'),
    path('search/', search, name='search'),
    path('delete-song/', delete_downloaded_song, name='delete'),
]

kelola_playlist/urls.py
from django.urls import path
from . import views
from kelola_playlist.views import playlist, playlist_detail, tambah_playlist, delete_playlist, edit_playlist, tambah_lagu, delete_song

app_name = 'kelola_playlist'

urlpatterns = [
    path('playlist/', playlist, name='playlist'),
    path('playlist_detail/<uuid:idPlaylist>/', playlist_detail, name='playlist_detail'),
    path('tambah_lagu/<uuid:idPlaylist>/', tambah_lagu, name='tambah_lagu'),
    path('tambah_playlist/', tambah_playlist, name='tambah_playlist'),
    path('delete_playlist/<uuid:idPlaylist>/', delete_playlist, name='delete_playlist'),
    path('edit_playlist/<uuid:idPlaylist>/', edit_playlist, name='edit_playlist'),
    path('delete_song/<uuid:playlist_id>/<uuid:song_id>/', delete_song, name='delete_song'),
   
]

marmut/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/auth/', permanent=False)),
    path('', include('album_song_royalti.urls')),
    path('', include('kelola_playlist.urls')),
    path('auth/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('kelola_podcast.urls')),
    path('', include('melihat_chart.urls')),
    path('', include('play_podcast.urls')),
    path('paket/', include('paket.urls')),
    path('', include('play_song.urls')),
]

paket/urls.py
from django.urls import path
from paket.views import paket, paket_payment, riwayat

app_name = 'paket'

urlpatterns = [
    path('', paket, name='paket'),
    path('riwayat/', riwayat, name='riwayat'),
    path('<str:nama_paket>/', paket_payment, name='paket_payment'),
]

play_podcast/urls.py
from django.urls import path
from play_podcast.views import play_podcast

app_name = 'play_podcast'

urlpatterns = [
    path('play-podcast/<uuid:podcast_id>/', play_podcast, name='play_podcast'),
]

play_song/urls.py
from django.urls import path
from . import views
from play_song.views import song_detail, song_detail_only, add_to_playlist_new, add_to_playlist

app_name = 'play_song'

urlpatterns = [   
    path('song_detail/<uuid:playlist_id>/<uuid:song_id>/', song_detail, name='song_detail'),
    path('song_detail/<uuid:song_id>/', song_detail_only, name='song_detail_only'),
    path('add_to_playlist/<uuid:playlist_id>/<uuid:song_id>/', add_to_playlist, name='add_to_playlist'),
    path('add_to_playlist/<uuid:song_id>/', add_to_playlist_new, name='add_to_playlist_new'),
    
]

dashboard/views.py
import uuid
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from utils.query import get_database_cursor
from datetime import datetime, timedelta

# Create your views here.
def get_album(id):
    connection, cursor = get_database_cursor()
    query = f"select * from album where id_label='{id}'"
    cursor.execute(query)
    albums = cursor.fetchall()
    # close connection
    cursor.close()
    connection.close()
    return albums

def get_playlist(email):
    connection, cursor = get_database_cursor()
    query = f"select * from user_playlist where email_pembuat='{email}'"
    cursor.execute(query)
    playlists = cursor.fetchall()
    # close connection
    cursor.close()
    connection.close()
    return playlists

def get_podcast(email):
    connection, cursor = get_database_cursor()
    query = f"""
    select * from podcast p
    join konten k on k.id = p.id_konten
    where email_podcaster='{email}'
    """
    cursor.execute(query)
    podcasts = cursor.fetchall()
    # close connection
    cursor.close()
    connection.close()
    return podcasts

def get_song(id_artist, id_songwriter):
    connection, cursor = get_database_cursor()
    if id_artist and id_songwriter:
        query = f"""
        select k.judul, k.id, k.tahun from song s
        join konten k on k.id = s.id_konten
        where s.id_artist='{id_artist}'

        union

        select k.judul, k.id, k.tahun from song s
        join konten k on k.id = s.id_konten
        join songwriter_write_song sws on sws.id_song = k.id
        where sws.id_songwriter='{id_songwriter}'
        """
    elif id_artist:
        query = f"""
        select k.judul, k.id, k.tahun from song s
        join konten k on k.id = s.id_konten
        where s.id_artist='{id_artist}'
        """
    else:
        query = f"""
        select k.judul, k.id, k.tahun from song s
        join konten k on k.id = s.id_konten
        join songwriter_write_song sws on sws.id_song = k.id
        where sws.id_songwriter='{id_songwriter}'
        """
    cursor.execute(query)
    songs = cursor.fetchall()
    # close connection
    cursor.close()
    connection.close()
    return songs

def dashboard(request):
    role = request.COOKIES.get('role')
    email = request.COOKIES.get('email')
    id_label = request.COOKIES.get('id')
    id_user_artist = request.COOKIES.get('id_user_artist')
    id_user_songwriter = request.COOKIES.get('id_user_songwriter')
    id_pemilik_hak_cipta_artist = request.COOKIES.get('idPemilikCiptaArtist')
    id_pemilik_hak_cipta_songwriter = request.COOKIES.get('idPemilikCiptaSongwriter')
    status_langganan = request.COOKIES.get('status_langganan')
    isArtist = request.COOKIES.get('isArtist')=='True'
    isSongwriter = request.COOKIES.get('isSongwriter')=='True'
    isPodcaster = request.COOKIES.get('isPodcaster')=='True'
    
    song, podcast, playlist, album = [], [], [], []
    connection, cursor = get_database_cursor()
    
    playlist = get_playlist(email)
    if isArtist or isSongwriter:
        song = get_song(id_user_artist, id_user_songwriter)
    if isPodcaster:
        podcast = get_podcast(email)

    if role == 'label':
        query = f"SELECT * FROM LABEL WHERE EMAIL='{email}'"
        album = get_album(id_label)
    else:
        query = f"SELECT * FROM AKUN WHERE EMAIL='{email}'"
    cursor.execute(query)
    user = cursor.fetchone()
    context = {
        'role': role,
        'status_langganan': status_langganan,
        'isArtist': isArtist,
        'isSongwriter': isSongwriter,
        'isPodcaster': isPodcaster,
        'email': email,
        'user' : user,
        'song' : song,
        'podcast' : podcast,
        'playlist' : playlist,
        'album' : album,
    }
    # close connection
    cursor.close()
    connection.close()

    return render(request, "dashboard.html", context)

def search(request):
    keyword = request.GET.get('q', None)
    connection, cursor = get_database_cursor()
    if keyword:
        query = f"""
            SELECT 'Podcast' AS Tipe, k.judul AS Judul, a.nama AS Oleh, k.id as ID
            FROM podcast p
            JOIN konten k ON p.id_konten = k.id
            JOIN akun a ON p.email_podcaster = a.email
            WHERE LOWER(k.judul) LIKE LOWER('%{keyword}%')

            UNION

            SELECT 'Song' AS Tipe, k.judul AS Judul, a.nama AS Oleh, k.id as ID
            FROM song s
            JOIN konten k ON s.id_konten = k.id
            JOIN artist art ON s.id_artist = art.id
            JOIN akun a ON art.email_akun = a.email
            WHERE LOWER(k.judul) LIKE LOWER('%{keyword}%')

            UNION

            SELECT 'User Playlist' AS Tipe, up.judul AS Judul, a.nama AS Oleh, up.id_playlist as ID
            FROM user_playlist up
            JOIN akun a ON up.email_pembuat = a.email
            WHERE LOWER(up.judul) LIKE LOWER('%{keyword}%')
            """
        cursor.execute(query)
        contents = cursor.fetchall()
        message = f"Hasil pencarian untuk \"{keyword}\""
        print(contents)
        if len(contents) == 0:
            message = f"Maaf, pencarian untuk \"{keyword}\" tidak ditemukan"

        context = {
            "contents": contents,
            "message" : message
        }

        # close connection
        cursor.close()
        connection.close()
        # print(paket)
        return render(request, "search.html", context)
    return render(request, "search.html")

def downloaded_songs(request):
    connection, cursor = get_database_cursor()
    email = request.COOKIES.get('email')

    cursor.execute(f"""
        select k.judul, a.nama, d.id_song from downloaded_song d
        JOIN konten k ON d.id_song = k.id
        JOIN song s ON d.id_song = s.id_konten
        JOIN artist art ON s.id_artist = art.id
        JOIN akun a ON art.email_akun = a.email
        WHERE d.email_downloader = '{email}'
    """
    )
    songs = cursor.fetchall()
    context = {
        "songs": songs
    }
    print(songs)

    # close connection
    cursor.close()
    connection.close()
    return render(request, "downloaded_songs.html", context)

def delete_downloaded_song(request):
    connection, cursor = get_database_cursor()
    email = request.COOKIES.get('email')
    id_song = request.GET.get('id_song')

    if not email:
        return HttpResponse("Error: No email found in cookies.", status=400)
    
    cursor.execute(f"""
        DELETE FROM DOWNLOADED_SONG
        WHERE id_song = '{id_song}' AND email_downloader ='{email}'
    """)
    cursor.execute(
            f"UPDATE SONG SET total_download = total_download - 1 WHERE id_konten = '{id_song}'"
        )
    connection.commit()
    # close connection
    cursor.close()
    connection.close()
    return JsonResponse({'message': 'Song deleted successfully', 'id_song': id_song})

dashboard/templates/dashboard.html
{% extends 'base_user.html' %}

{% block meta %}
    <title>Dashboard</title>
    <style>
      .bg-yellow{
        background-color: #c6c639;
      }
      .bg-green{
        background-color: #97b51d;
      }

      .container{
        min-height: 100vh;
      }

      .text-white {
        color: white;
      }

      .divider{
        background-color: white;
        height: 1px;
        width: 100%;
      }
    </style>
{% endblock meta %}

{% block content %}
<style></style>
<div class="container border p-lg-5 text-white text-center">
    <div class="bg-dark d-flex flex-column justify-content-center align-items-center rounded p-lg-5">
      {% if role == 'label' %}
      <h2 class="mb-5">Label Dashboard</h2>
      <div class="row bg-primary p-3 rounded w-50">
        <div class="col">
          <div class="d-flex flex-column m-3">
            Nama
            <b>{{user.1}}</b>
          </div>
          <div class="d-flex flex-column m-3">
            Email
            <b>{{email}}</b>
          </div>
          <div class="d-flex flex-column m-3">
            Kontak
            <b>{{user.4}}</b>
          </div>
        </div>
      </div>
      {% else %}
      <h2 class="mb-5">User Dashboard</h2>
      <div class="row bg-primary p-3 rounded w-50">
        <div class="col">
          <div class="d-flex flex-column align-items-start m-3">
            Name
            <b>{{user.2}}</b>
          </div>
          <div class="d-flex flex-column align-items-start m-3">
            Email
            <b>{{email}}</b>
          </div>
          <div class="d-flex flex-column align-items-start m-3">
            Kota Asal
            <b>{{user.7}}</b>
          </div>
          <div class="d-flex flex-column align-items-start m-3">
            Gender
            {% if user.3 == 1%}
            <b>Laki-laki</b>
            {% else %}
            <b>Perempuan</b>
            {% endif %}
          </div>
        </div>
        <div class="col">
            <div class="d-flex flex-column align-items-start m-3">
                Tempat Lahir
                <b>{{user.4}}</b>
              </div>
              <div class="d-flex flex-column align-items-start m-3">
                Tanggal Lahir
                <b>{{user.5}}</b>
              </div>
              <div class="d-flex flex-column align-items-start m-3">
                Role
                <b>{{role}}</b>
              </div>
        </div>
      </div>
      {% endif %}
      <hr class="divider">
      {% if role == 'label' %}
      <section class="row py-5">
        <h2 class="mb-5">Daftar Album</h2>
        <div class="d-flex flex-wrap justify-content-center gap-5">
          {% if not album %}
          <p>Tidak memiliki album</p>
          {% else %}
            {% for item in album %}
            <div class="card w-50">
              <div class="card-body">
                <h5 class="card-title">{{item.1}}</h5>
                <p class="card-text">{{item.2}} songs</p>
                <p class="card-text">{{item.4}} mins</p>
                <a href="{% url 'album_song_royalti:list_song' %}?id={{item.0}}" class="btn btn-primary">View Album</a>
              </div>
            </div>
            {% endfor %}
          {% endif %}
        </div>
      </section>
      {% else %}
      <section class="row py-5">
        <h2 class="mb-5">Daftar Playlist</h2>
        <div class="d-flex flex-wrap justify-content-center gap-5">
          {% if not playlist %}
          <p>Tidak memiliki playlist</p>
          {% else %}
            {% for item in playlist %}
            <div class="card w-50">
              <div class="card-body">
                <h5 class="card-title">{{item.2}}</h5>
                <p class="card-text">{{item.3}}</p>
                <p class="card-text">{{item.7}} mins</p>
                <a href="{% url 'kelola_playlist:playlist_detail' item.6%}" class="btn btn-primary">View Playlist</a>
              </div>
            </div>
            {% endfor %}
          {% endif %}
        </div>
      </section>
      {% endif %}
      {% if isPodcaster %}
      <section class="row py-5">
        <h2 class="mb-5">Daftar Podcast </h2>
        <div class="d-flex flex-wrap justify-content-center gap-5">
          {% if not podcast %}
          <p>Tidak memiliki podcast</p>
          {% else %}
            {% for item in podcast %}
            <div class="card w-25">
              <div class="card-body">
                <h5 class="card-title">{{item.3}}</h5>
                <p class="card-text">{{item.5}}</p>
                <a href="{% url 'play_podcast:play_podcast' item.0 %}" class="btn btn-primary">View Podcast</a>
              </div>
            </div>
            {% endfor %}
          {% endif %}
        </div>
      </section>
      {% endif %}
      {% if isArtist or isSongwriter %}
      <section class="row py-5">
        <h2 class="mb-5">Daftar Lagu </h2>
        <div class="d-flex flex-wrap justify-content-center gap-5">
          {% if not song %}
          <p>Tidak memiliki lagu</p>
          {% else %}
            {% for item in song %}
            <div class="card w-25">
              <div class="card-body">
                <h5 class="card-title">{{item.0}}</h5>
                <p class="card-text">{{item.2}}</p>
                <a href="{% url 'play_song:song_detail_only' item.1 %}" class="btn btn-primary">View Song</a>
              </div>
            </div>
            {% endfor %}
          {% endif %}
        </div>
      </section>
      {% endif %}
    </div>
  </div>

{% endblock content %}

dashboard/templates/downloaded_songs.html
{% extends 'base_user.html' %}

{% block meta %}
    <title>Dashboard</title>
    <style>
      .bg-yellow{
        background-color: #c6c639;
      }
      .bg-green{
        background-color: #97b51d;
      }

      .container{
        min-height: 100vh;
      }

      .text-white {
        color: white;
      }

      .modal {
            display: flex;
            justify-content: center;
            align-items: center;
            position: fixed; 
            z-index: 1; 
            left: 0;
            top: 0;
            width: 100%; 
            height: 100%; 
            overflow: auto; 
            background-color: rgb(0,0,0); 
            background-color: rgba(0,0,0,0.4); 
            padding-top: 60px;
        }

        .modal-content {
            max-width: 25%;
            padding: 1rem;
        }
    </style>
{% endblock meta %}

{% block content %}
<div class="container border p-lg-5 text-white text-center">
    <div class="bg-dark d-flex flex-column justify-content-center align-items-center rounded p-lg-5">
      <h2 class="mb-5">DAFTAR LAGU</h2>
      <table class="table table-striped">
        <thead class="table-primary rounded">
            <tr>
              <th scope="col">Judul</th>
              <th scope="col">Oleh</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for song in songs %}
            <tr data-id="{{ song.2 }}">
              <td>{{song.0}}</td>
              <td>{{song.1}}</td>
              <td>
                <a href="{% url 'play_song:song_detail_only' song.2 %}" class="btn btn-primary">Lihat</a>
                <button type="button" data-title="{{song.0}}" class="btn btn-danger openModalBtn">
                    Hapus
                </button>
              </td>
            </tr>
            {% endfor %}
          </tbody>
      </table>
    </div>
  </div>
<!-- The Modal -->
<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <p class="text-center mb-4" id="modalText">Some text in the Modal..</p>
    <div class="d-flex justify-content-end">
      <span class="close btn btn-secondary">Kembali</span>
    </div>
  </div>

</div>

<script>
  // Get the modal
  var modal = document.getElementById("myModal");

// Get all buttons that open the modal
var btns = document.querySelectorAll(".openModalBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// Loop through all buttons and attach the click event to each
btns.forEach(function(btn) {
    btn.onclick = async function() {
        var songId = btn.closest('tr').getAttribute('data-id');
        var songTitle = btn.getAttribute('data-title');
        await fetch(`{% url 'dashboard:delete' %}?id_song=${songId}`, {
                    method: 'GET',
                })
                .then(response => response.json())
                .then(data => {
                    if(data.message === 'Song deleted successfully') {
                        document.getElementById('modalText').innerText = `
                        Berhasil menghapus Lagu dengan judul '${songTitle}' dari daftar unduhan!`;
                        // Optionally remove the row from the table
                        this.closest('tr').remove();
                    }
                })
                .catch(error => console.error('Error:', error));
        // alert(songTitle)
        modal.style.display = "flex";
    }
});

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>
{% endblock content %}

dashboard/templates/paket_payment.html
{% extends 'base_user.html' %}

{% block meta %}
    <title>Dashboard</title>
    <style>
      .bg-yellow{
        background-color: #c6c639;
      }
      .bg-green{
        background-color: #97b51d;
      }

      .container{
        min-height: 100vh;
      }

      .text-white {
        color: white;
      }
    </style>
{% endblock meta %}

{% block content %}
<style></style>
<div class="container border p-lg-5 text-white text-center">
    <div class="bg-dark d-flex flex-column justify-content-center align-items-center rounded p-lg-5">
      <h2 class="mb-5">Pembayaran Paket</h2>
      <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header fs-5">
                  1 Bulan
                </div>
                <div class="card-body">
                  <h5 class="card-title">
                    <span class="fs-4">Rp</span>
                    <span class="fs-2">35</span><span class="fs-6">.000</span>
                </h5>
                <ul class="card-text">
                    <li>Bebas iklan dalam konten</li>
                    <li>Akses Konten VIP</li>
                    <li>Download lagu favoritmu</li>
                </ul>
                </div>
            </div>
        </div>
      </div>
      <form>
          <select class="form-select mb-3 mt-5" aria-label="example">
            <option selected>Pilih metode pembayaran</option>
            <option value="1">Transfer Bank</option>
            <option value="2">OVO</option>
            <option value="3">DANA</option>
          </select>
          <input class="btn btn-primary" type="button" name="submit" id="submit" value="Bayar">
      </form>
    </div>
  </div>

{% endblock content %}

dashboard/templates/riwayat.html
{% extends 'base_user.html' %}

{% block meta %}
    <title>Dashboard</title>
    <style>
      .bg-yellow{
        background-color: #c6c639;
      }
      .bg-green{
        background-color: #97b51d;
      }

      .container{
        min-height: 100vh;
      }

      .text-white {
        color: white;
      }
    </style>
{% endblock meta %}

{% block content %}
<style></style>
<div class="container border p-lg-5 text-white text-center">
    <div class="bg-dark d-flex flex-column justify-content-center align-items-center rounded p-lg-5">
      <h2 class="mb-5">RIWAYAT TRANSAKSI PAKET</h2>
      <table class="table table-striped">
        <thead class="table-primary">
            <tr>
              <th scope="col">Jenis</th>
              <th scope="col">Tanggal Dimulai</th>
              <th scope="col">Tanggal Berakhir</th>
              <th scope="col">Metode Pembayaran</th>
              <th scope="col">Nominal</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">1 Bulan</th>
              <td>8 April 2024 17.23</td>
              <td>8 Mei 2024 17.23</td>
              <td>OVO</td>
              <td>Rp35.000</td>
            </tr>
            <tr>
              <th scope="row">1 Bulan</th>
              <td>8 Mei 2024 17.23</td>
              <td>8 Juni 2024 17.23</td>
              <td>DANA</td>
              <td>Rp35.000</td>
            </tr>
            <tr>
              <th scope="row">3 Bulan</th>
              <td>8 Agustus 2024 17.23</td>
              <td>8 November 2024 17.23</td>
              <td>Transfer Bank</td>
              <td>Rp99.000</td>
            </tr>
          </tbody>
      </table>
      <a href="{% url 'dashboard:paket' %}" class="btn btn-primary">Kembali</a>
    </div>
  </div>

{% endblock content %}

dashboard/templates/search.html
{% extends 'base_user.html' %}

{% block meta %}
    <title>Dashboard</title>
    <style>
      .bg-yellow{
        background-color: #c6c639;
      }
      .bg-green{
        background-color: #97b51d;
      }

      .container{
        min-height: 100vh;
      }

      .text-white {
        color: white;
      }
    </style>
{% endblock meta %}

{% block content %}
<div class="container border p-lg-5 text-white text-center">
    <div class="bg-dark d-flex flex-column justify-content-center align-items-center rounded p-lg-5">
        <form class="d-flex justify-content-center w-75 mb-5" method="get" id="search-form" style="display: none;">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
            <button class="btn btn-light" type="submit">Search</button>
        </form>
      <h2 class="mb-5">{{message}}</h2>
      {% if contents %}
      <table class="table table-striped">
        <thead class="table-primary rounded">
            <tr>
              <th scope="col">Type</th>
              <th scope="col">Judul</th>
              <th scope="col">Oleh</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for item in contents %}
              <tr>
                <th scope="row">{{item.0}}</th>
                <td>{{item.1}}</td>
                <td>{{item.2}}</td>
                <td>
                    {% if item.0 == 'Podcast' %}
                        <a href="{% url 'play_podcast:play_podcast' item.3 %}" class="btn btn-primary">Lihat</a>
                    {% elif item.0 == 'Song' %}
                        <a href="{% url 'play_song:song_detail_only' item.3 %}" class="btn btn-primary">Lihat</a>
                    {% else %}
                        <a href="{% url 'kelola_playlist:playlist_detail' item.3 %}" class="btn btn-primary">Lihat</a>
                    {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
      </table>
      {% endif %}
    </div>
  </div>

{% endblock content %}